# Pre-commit hooks for code quality, security, and policy enforcement
# Install: pip install pre-commit
# Setup: pre-commit install && pre-commit install --hook-type commit-msg
# Run manually: pre-commit run --all-files

repos:
  # Code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=120]

  # Linting and code quality
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--max-line-length=120, --extend-ignore=E203,W503]
        additional_dependencies: [flake8-docstrings, flake8-bugbear]

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-c, .bandit, -r]
        exclude: ^tests/
