name: "ðŸž Bug report"
description: Report a bug found while using the TestRail CLI.
body:
  - type: input
    id: cli-version
    attributes:
      label: TestRail CLI Version
      description: You can check the version by just executing `trcli` or `pip show trcli` on your command line.
      placeholder: ex. 1.1.0
    validations:
      required: true
  - type: textarea
    id: cli-system
    attributes:
      label: CLI Environment
      description: Information about operating system, python version, etc
      placeholder: ex. Windows 10 Pro, Python 3.10.2, etc
  - type: input
    id: testrail-version
    attributes:
      label: TestRail Version
      description: You can check your TestRail version on `Help & Feedback` > `About TestRail` on the top right corner.
      placeholder: ex. 7.3.0.3040
    validations:
      required: true
  - type: dropdown
    id: testrail-type
    attributes:
      label: TestRail Instance Type
      description: Your TestRail installation type. This can be found on the Administration page.
      options:
        - Professional Cloud
        - Professional Server
        - Enterprise Cloud
        - Enterprise Server
        - NA
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Add a short description of the issue, screenshots, logs, command being executed, config files, report samples, etc.
      placeholder: Currently...
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behavior
      description: Explain what would be the expected behavior for the situation you just described.
      placeholder: I would expect that...
  - type: textarea
    id: more-details
    attributes:
      label: More Details
      placeholder: Other details you would like to include.
