MAX_WORKERS_ADD_CASE = 10
MAX_WORKERS_ADD_RESULTS = 20
DEFAULT_API_CALL_RETRIES = 5
DEFAULT_API_CALL_TIMEOUT = 60
DEFAULT_BATCH_SIZE = 50
ALLOW_ELAPSED_MS = False
ENABLE_PARALLEL_PAGINATION = False
MAX_WORKERS_PARALLEL_PAGINATION = 10
