from pathlib import Path

import click
import yaml

from trcli.api.api_request_handler import ApiRequestHandler
from trcli.cli import CONTEXT_SETTINGS, Environment, pass_environment
from trcli.cli_styles import StyledCommand, style_text
from trcli.commands.cmd_status import _build_api_client, _validate_host
from trcli.constants import ProjectErrors, SuiteModes
from trcli.data_classes.dataclass_testrail import ProjectData, TestRailSuite
from trcli.settings import DEFAULT_API_CALL_TIMEOUT, DEFAULT_BATCH_SIZE


def _echo(message: str, color: str = "muted", *, bold: bool = False, err: bool = False):
    ctx = click.get_current_context(silent=True)
    click.echo(style_text(message, color, ctx=ctx, bold=bold), err=err)


def _prompt(message: str, **kwargs):
    ctx = click.get_current_context(silent=True)
    return click.prompt(style_text(message, "accent_bright", ctx=ctx, bold=True), **kwargs)


def _prompt_host() -> str:
    while True:
        host = _prompt("TestRail host", type=click.STRING).strip()
        if _validate_host(host):
            return host
        _echo("Enter a full URL such as https://example.testrail.io", "error", err=True)


def _prompt_auth_method() -> str:
    _echo("Authentication:", "accent")
    _echo("  1. API key (recommended)")
    _echo("  2. Password")
    return _prompt("Select auth method", type=click.Choice(["1", "2"]), default="1", show_choices=False)


def _build_config_data(
    host: str,
    project: str,
    project_id: int | None,
    username: str,
    auth_method: str,
    secret: str,
    suite_id: int | None = None,
    proxy: str | None = None,
    proxy_user: str | None = None,
    noproxy: str | None = None,
    insecure: bool = False,
    timeout: float | None = None,
    batch_size: int | None = None,
) -> dict:
    data = {
        "host": host,
        "project": project,
        "username": username,
    }
    if project_id:
        data["project_id"] = project_id
    if auth_method == "1":
        data["key"] = secret
    else:
        data["password"] = secret
    if suite_id:
        data["suite_id"] = suite_id
    if proxy:
        data["proxy"] = proxy
    if proxy_user:
        data["proxy_user"] = proxy_user
    if noproxy:
        data["noproxy"] = noproxy
    if insecure:
        data["insecure"] = True
    if timeout is not None:
        data["timeout"] = timeout
    if batch_size is not None:
        data["batch_size"] = batch_size
    return data


def _write_config(output_path: Path, data: dict):
    header = [
        "# Generated by `trcli init`.",
        "# Keep this file out of version control if it contains secrets.",
        "",
    ]
    yaml_content = yaml.safe_dump(data, sort_keys=False, default_flow_style=False)
    with open(output_path, "w", encoding="utf-8") as config_file:
        config_file.write("\n".join(header))
        config_file.write(yaml_content)


def _configure_advanced_settings() -> dict:
    ctx = click.get_current_context(silent=True)
    if not click.confirm(
        style_text(
            "Configure advanced connection settings (proxy, SSL, timeout, batch size)?",
            "accent_bright",
            ctx=ctx,
            bold=True,
        ),
        default=False,
    ):
        return {}

    _echo("")
    _echo("Advanced settings:", "accent")
    proxy = _prompt("Proxy URL", default="", show_default=False).strip() or None
    proxy_user = None
    noproxy = None
    if proxy:
        proxy_user = _prompt("Proxy credentials username:password", default="", show_default=False).strip() or None
        noproxy = _prompt("No-proxy hosts (comma-separated)", default="", show_default=False).strip() or None
    insecure = click.confirm(
        style_text("Allow insecure SSL?", "accent_bright", ctx=ctx, bold=True),
        default=False,
    )
    timeout = _prompt("Request timeout in seconds", type=float, default=DEFAULT_API_CALL_TIMEOUT, show_default=True)
    batch_size = _prompt("Batch size", type=click.IntRange(min=2), default=DEFAULT_BATCH_SIZE, show_default=True)
    return {
        "proxy": proxy,
        "proxy_user": proxy_user,
        "noproxy": noproxy,
        "insecure": insecure,
        "timeout": timeout,
        "batch_size": batch_size,
    }


def _resolve_project_context(environment: Environment) -> tuple[ProjectData | None, ApiRequestHandler | None]:
    try:
        api_handler = ApiRequestHandler(
            environment=environment,
            api_client=_build_api_client(environment),
            suites_data=TestRailSuite(name="init"),
            verify=False,
        )
        project_data = api_handler.get_project_data(environment.project, environment.project_id)
        if project_data.project_id > 0:
            return project_data, api_handler
        return project_data, api_handler
    except Exception:
        return None, None


def _configure_suite_id(environment: Environment) -> int | None:
    project_data, api_handler = _resolve_project_context(environment)
    if project_data and project_data.project_id > 0:
        _echo("")
        _echo(f"Project validation: OK (ID {project_data.project_id})", "success")
        if not environment.project_id:
            environment.project_id = project_data.project_id

        if project_data.suite_mode == SuiteModes.single_suite:
            suite_ids, error = api_handler.get_suite_ids(project_data.project_id)
            if not error and len(suite_ids) == 1:
                ctx = click.get_current_context(silent=True)
                if click.confirm(
                    style_text("Store the detected default Suite ID in config?", "accent_bright", ctx=ctx, bold=True),
                    default=False,
                ):
                    return suite_ids[0]
                return None
            _echo("This project uses a single suite. Storing a Suite ID is optional.", "muted")
        else:
            _echo("This project can use explicit Suite IDs. A default Suite ID is optional.", "muted")
    elif project_data and project_data.project_id in [
        ProjectErrors.multiple_project_same_name,
        ProjectErrors.not_existing_project,
        ProjectErrors.other_error,
    ]:
        _echo(f"Project validation skipped: {project_data.error_message}", "warn")
    else:
        _echo("Project validation skipped. You can still save a Suite ID manually.", "warn")

    ctx = click.get_current_context(silent=True)
    if not click.confirm(
        style_text("Configure a default Suite ID for this project?", "accent_bright", ctx=ctx, bold=True),
        default=False,
    ):
        return None

    while True:
        suite_id = _prompt("Default Suite ID", type=click.IntRange(min=1))
        if project_data and project_data.project_id > 0 and api_handler:
            api_handler.suites_data_from_provider.suite_id = suite_id
            suite_exists, error_message = api_handler.check_suite_id(project_data.project_id)
            if suite_exists:
                _echo(f"Suite validation: OK (ID {suite_id})", "success")
                return suite_id
            _echo(error_message, "error", err=True)
            continue
        return suite_id


@click.command(name="init", cls=StyledCommand, context_settings=CONTEXT_SETTINGS)
@click.option(
    "--output",
    type=click.Path(dir_okay=False, path_type=Path),
    default=Path("config.yml"),
    show_default=True,
    help="Path to the generated TRCLI config file.",
)
@click.option(
    "--overwrite",
    is_flag=True,
    help="Overwrite an existing config file without prompting.",
)
@pass_environment
def cli(environment: Environment, output: Path, overwrite: bool):
    """Interactively create a starter TRCLI config file"""
    environment.cmd = "init"

    _echo("TRCLI initialization", "accent", bold=True)
    _echo("This wizard writes a starter config file for the current workspace.")
    _echo("")

    output_path = output.expanduser().resolve()
    if output_path.exists() and not overwrite:
        replace = click.confirm(
            style_text(
                f"{output_path} already exists. Overwrite it?",
                "warn",
                ctx=click.get_current_context(silent=True),
            )
        )
        if not replace:
            _echo("Initialization cancelled. Existing config was left unchanged.", "warn")
            raise click.Abort()

    host = _prompt_host()
    project = _prompt("Default project name", type=click.STRING).strip()
    project_id = _prompt("Project ID if needed for duplicate names", default="", show_default=False).strip()
    username = _prompt("Username", type=click.STRING).strip()
    auth_method = _prompt_auth_method()
    secret_label = "API key" if auth_method == "1" else "Password"
    secret = _prompt(secret_label, hide_input=True, confirmation_prompt=True, type=click.STRING).strip()
    environment.host = host
    environment.project = project
    environment.project_id = int(project_id) if project_id else None
    environment.username = username
    environment.password = secret if auth_method == "2" else None
    environment.key = secret if auth_method == "1" else None

    advanced_settings = _configure_advanced_settings()
    for key, value in advanced_settings.items():
        setattr(environment, key, value)

    suite_id = _configure_suite_id(environment)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    config_data = _build_config_data(
        host=host,
        project=project,
        project_id=environment.project_id,
        username=username,
        auth_method=auth_method,
        secret=secret,
        suite_id=suite_id,
        proxy=advanced_settings.get("proxy"),
        proxy_user=advanced_settings.get("proxy_user"),
        noproxy=advanced_settings.get("noproxy"),
        insecure=advanced_settings.get("insecure", False),
        timeout=advanced_settings.get("timeout"),
        batch_size=advanced_settings.get("batch_size"),
    )
    _write_config(output_path, config_data)

    _echo("")
    _echo("Saved configuration:", "accent")
    _echo(f"  Path: {output_path}", "muted")
    _echo(f"  Host: {host}", "muted")
    _echo(f"  Project: {project}", "muted")
    _echo(f"  Auth: {'username + API key' if auth_method == '1' else 'username + password'}", "muted")
    if suite_id:
        _echo(f"  Suite ID: {suite_id}", "muted")
    if advanced_settings:
        _echo("  Advanced settings: configured", "muted")
    _echo("")
    _echo("Next step: run `trcli status` to verify the saved configuration.", "success")
